global:
  imagePullPolicy: IfNotPresent
  jwtSecret: devsecret
  databaseUrl: postgres://postgres:postgres@postgres:5432/market

postgres:
  enabled: true
  image: postgres:16-alpine
  storage: 2Gi
  username: postgres
  password: postgres
  database: market

uploads:
  storage: 2Gi

ingress:
  enabled: false
  className: nginx
  host: kharseka.local
  tlsEnabled: false
  tlsSecretName: kharseka-tls

gateway:
  image: api-gateway
  tag: local
  replicas: 1
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { cpu: 500m, memory: 512Mi }

services:
  auth:
    image: auth-service
    tag: local
    replicas: 1
    resources:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 500m, memory: 512Mi }
  listings:
    image: listings-service
    tag: local
    replicas: 1
    resources:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 500m, memory: 512Mi }
  favorites:
    image: favorites-service
    tag: local
    replicas: 1
    resources:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 500m, memory: 512Mi }
  media:
    image: media-service
    tag: local
    replicas: 1
    resources:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 500m, memory: 512Mi }

hpa:
  gateway:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  listings:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
