apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
  labels:
    app: favorites-service
  annotations:
     argocd-image-updater.argoproj.io/update-strategy: "latest"
spec:
  replicas: {{ .Values.services.favorites.replicas }}
  selector:
    matchLabels: { app: favorites-service }
  template:
    metadata:
      labels: { app: favorites-service }
    spec:
      containers:
      - name: favorites-service
        image: {{ .Values.services.favorites.image }}:{{ .Values.services.favorites.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports: [{ containerPort: 3003 }]
        resources:
{{ toYaml .Values.services.favorites.resources | indent 10 }}
        readinessProbe:
          httpGet: { path: /healthz, port: 3003 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 3003 }
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: favorites-service
spec:
  type: ClusterIP
  selector: { app: favorites-service }
  ports:
  - port: 3003
    targetPort: 3003
