apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    {{- include "kharseka.labels" . | nindent 4 }}
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: "latest"
    argocd-image-updater.argoproj.io/gateway: "${{ secrets.DOCKERHUB_USERNAME }}/kharseka-gateway"
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
      - name: gateway
        image: {{ .Values.gateway.image }}:{{ .Values.gateway.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: AUTH_URL
          value: http://auth-service:3001
        - name: LISTINGS_URL
          value: http://listings-service:3002
        - name: FAVORITES_URL
          value: http://favorites-service:3003
        - name: MEDIA_URL
          value: http://media-service:3004
        ports: [{ containerPort: 3000 }]
        resources:
{{ toYaml .Values.gateway.resources | indent 10 }}
        readinessProbe:
          httpGet: { path: /healthz, port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector: { app: api-gateway }
  ports:
  - port: 80
    targetPort: 3000
