apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    app: media-service
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: "digest"
spec:
  replicas: {{ .Values.services.media.replicas }}
  selector:
    matchLabels: { app: media-service }
  template:
    metadata:
      labels: { app: media-service }
    spec:
      containers:
      - name: media-service
        image: {{- if (regexMatch "^sha256:" .Values.services.media.tag) }}{{ .Values.services.media.image }}@{{ .Values.services.media.tag }}{{ else }}{{ .Values.services.media.image }}:{{ .Values.services.media.tag }}{{ end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports: [{ containerPort: 3004 }]
        {{- if .Values.services.media.resources }}
        resources:
      {{ toYaml .Values.services.media.resources | indent 10 }}
        {{- end }}
        readinessProbe:
          httpGet: { path: /healthz, port: 3004 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 3004 }
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  type: ClusterIP
  selector: { app: media-service }
  ports:
  - port: 3004
    targetPort: 3004
