apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kharseka.fullname" . }}-secrets
  labels:
    {{- include "kharseka.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  DATABASE_URL: {{ .Values.global.databaseUrl | quote }}
